#!/usr/bin/bash

if [[ -n "$MC_SID" ]]; then
  exit 0
fi

GRANDPARENT_PROCESS=$(ps -o comm= -p $(ps -o ppid= -p $PPID))
if [[ "$GRANDPARENT_PROCESS" != "dolphin" ]]; then
  echo "" && /usr/bin/fastfetch --color "0;38;2;240;80;180" -c /usr/share/ublue-os/theledora/fastfetch.jsonc && echo ""
fi
